"""Apply batch fixes from agents to DM1 openers CSV."""

import csv

CSV_PATH = "data/rev-leaders-v2-dm1-openers.csv"

FIXES_BATCH1 = {
    "chris.ward@jellyfish.co": "Great to connect. Chris, was looking at Jellyfish trying to understand how the team is positioning engineering ops tooling on outbound. Are buyers coming inbound from the DevEx conversation or is the team running cold outbound into eng leadership? Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "emad.almarzoog@hcss.com": "Great to connect. Emad, was looking at HCSS trying to understand how the SDR team is reaching heavy-construction buyers who still run most of their ops on spreadsheets and legacy systems. Curious to hear how others selling into construction tech are building pipeline right now, Scott.",
    "misbahf@testmuai.com": "Great to connect. Misbah, was looking at TestMu AI and trying to understand how the founding-team pitch is landing against buyers who already knew the LambdaTest name. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "ryan.knisley@axonius.com": "Great to connect. Ryan, was looking at Axonius trying to understand how the team separates real asset-visibility pain from buyers who think they already solved it with their CMDB. Curious to hear how others selling into cybersecurity are building pipeline right now, Scott.",
    "bryan.maxwell@maxio.com": "Great to connect. Bryan, was looking at Maxio and trying to understand what the outbound conversation looks like when you're selling against native billing in Stripe. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "tbrown@invoicecloud.com": "Great to connect. Tom, was looking at InvoiceCloud and trying to understand what signals your team watches for a muni or utility that's actually ready to replace legacy billing. Curious to hear how others selling into government tech are building pipeline right now, Scott.",
    "feras.abdel@buildops.com": "Great to connect. Feras, was looking at BuildOps and trying to understand how the team built the revenue systems for a vertical SaaS selling into commercial contractors. Curious to hear how others selling into construction tech are building pipeline right now, Scott.",
    "tae@branch.io": "Great to connect. Tae, was looking at Branch and trying to understand how the Branch team is thinking about signal-based outbound to mobile product teams right now. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "christopher.pielock@tsimagine.com": "Great to connect. Chris, was looking at TS Imagine and trying to understand how your team separates buy-side from sell-side signals when going outbound. Curious to hear how others selling into financial services are building pipeline right now, Scott.",
    "brendan.peregrine@profitsolv.com": "Great to connect. Brendan, was looking at ProfitSolv and trying to understand what outbound feels like when the team is selling practice management into law firms that still run on manual billing. Curious to hear how others selling into legal and compliance tech are building pipeline right now, Scott.",
    "cole.helmer@xtech.ai": "Great to connect. Cole, was looking at XTEL and trying to understand how outbound plays when your ICP is CPG brands vs. the retailers themselves. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "josh@traildsoftware.com": "Great to connect. Josh, was looking at Traild and trying to understand what outbound looks like now that your buyer is a finance controller instead of a sales leader. Curious to hear how others selling into financial services are building pipeline right now, Scott.",
    "hector.ayala@aurigo.com": "Great to connect. Hector, was looking at Aurigo Software and trying to understand how the team separates the public-sector buyer from private-sector on outbound. Curious to hear how others selling into construction tech are building pipeline right now, Scott.",
    "jamie.kurtz@knime.com": "Great to connect. Jamie, was looking at KNIME and trying to understand what the outbound conversation sounds like when you're selling against Alteryx in the low-code data space. Curious to hear how others selling into data and analytics are building pipeline right now, Scott.",
    "kloucks@anteriad.com": "Great to connect. Kiara, was looking at Anteriad and trying to understand what outbound feels like now that B2B intent has gotten crowded. Curious to hear how others selling into ad and marketing tech are building pipeline right now, Scott.",
    "t.doyle@retool.com": "Great to connect. Tim, was looking at Retool and trying to understand what outbound plays are working now that internal tooling budget has tightened across the SaaS buyer universe. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "dan.oleary@lrn.com": "Great to connect. Dan, was looking at LRN and trying to understand what outbound looks like when you're selling ethics and compliance training into a buyer who already has five tools for adjacent use cases. Curious to hear how others selling into legal and compliance tech are building pipeline right now, Scott.",
    "henry.sanford@trimech.com": "Great to connect. Henry, was looking at TriMech and trying to understand what outbound plays are working for you when the buyer is an aerospace or defense engineering manager. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "nick.butrym@appzen.com": "Great to connect. Nick, was looking at AppZen and trying to understand what outbound plays are working now that AI spend management is competing against the incumbent T&E platforms for budget. Curious to hear how others selling into financial services are building pipeline right now, Scott.",
    "larry.anderson@commandlink.com": "Great to connect. Larry, was looking at CommandLink and trying to understand what outbound looks like when the buyer is an IT ops leader evaluating managed-SD-WAN providers. Curious to hear how others selling into telecom are building pipeline right now, Scott.",
    "richard.ortega@micrologic.net": "Great to connect. Richard, was looking at Micrologic and trying to understand what outbound plays work when the team is selling managed IT and VoIP into mid-market buyers who already have a provider. Curious to hear how others selling into telecom are building pipeline right now, Scott.",
    "mhull@meevo.com": "Great to connect. Melanie, was looking at Millennium Systems International and trying to understand what outbound looks like when you're selling into independent med spas that operate more like a boutique than a salon chain. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "amber.king@poppulo.com": "Great to connect. Amber, was looking at Poppulo and trying to understand what outbound plays are working when your buyer is an internal comms leader rather than IT. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "daren.jennings@interactsoftware.com": "Great to connect. Daren, was looking at Interact Software and trying to understand what outbound actually looks like when your buyer is a comms leader inside an enterprise HRIS stack. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "bruce.parkhurst@motive.com": "Great to connect. Bruce, was looking at Motive and trying to understand how the outbound conversation is shifting now that trucking telematics is less about GPS and more about AI and cameras. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "shavona.robinson@checksammy.com": "Great to connect. Shavona, was looking at CheckSammy and trying to understand how outbound works when your ICP is a facilities or sustainability lead rather than a procurement generalist. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "justin.kolman@megaport.com": "Great to connect. Justin, was looking at Megaport and trying to understand what outbound signals actually catch an enterprise architect at the moment they decide to add an interconnect partner. Curious to hear how others selling into telecom are building pipeline right now, Scott.",
    "suhas.harihar@asteralabs.com": "Great to connect. Suhas, was looking at Astera Labs and trying to understand what outbound looks like when your ICP is a hyperscaler ODM or a large AI lab building custom silicon systems. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "brandon.crouch@lightcast.io": "Great to connect. Brandon, was looking at Lightcast and trying to understand what outbound plays work when the team is selling labor market data into HR and economic development buyers. Curious to hear how others selling into data and analytics are building pipeline right now, Scott.",
    "hans.unger@nearmap.com": "Great to connect. Hans, was looking at Nearmap and trying to understand what patterns repeat on outbound signal quality when the buyer could be insurance, government, or construction depending on the use case. Curious to hear how others selling into data and analytics are building pipeline right now, Scott.",
    "caroline.kirbymadden@ceros.com": "Great to connect. Caroline, was looking at Ceros and trying to understand what outbound plays work when the buyer is a brand marketer evaluating interactive content against static landing pages. Curious to hear how others selling into ad and marketing tech are building pipeline right now, Scott.",
    "justin.stuck@alludo.com": "Great to connect. Justin, was looking at Parallels and trying to understand what outbound looks like for your team given how much of the EUC buyer's attention is on AI-desktop budget rather than Parallels specifically. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "will.davy@vantaca.com": "Great to connect. Will, was looking at Vantaca and trying to understand what outbound signals tell the team when an HOA management company is actually ready to switch platforms vs. just running evaluations. Curious to hear how others selling into real estate tech are building pipeline right now, Scott.",
    "maelyn.rexach@odpbusiness.com": "Great to connect. Maelyn, was looking at ODP Business Solutions and trying to understand what outbound plays actually land in a category where the buyer side is heavily procurement-driven and contract-heavy. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "theodore.engel@harness.io": "Great to connect. Eunice, was looking at Harness and trying to understand what you've seen move fastest on outbound to platform engineering leaders. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "neel.sinha@deque.com": "Great to connect. Neel, was looking at Deque Systems and trying to understand what outbound plays work for a buyer whose mandate is legal compliance but whose peers are still learning what ADA digital means. Curious to hear how others selling into legal and compliance tech are building pipeline right now, Scott.",
    "andy.renda@hungerrush.com": "Great to connect. Andrew, was looking at HungerRush and trying to understand what outbound plays work when the buyer is an independent restaurant operator evaluating POS and online ordering against Toast and Square. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "bferreira@hhaexchange.com": "Great to connect. Ben, was looking at HHAeXchange and trying to understand what outbound plays work now that homecare agencies are under margin pressure from both Medicaid and EVV compliance. Curious to hear how others selling into healthcare tech are building pipeline right now, Scott.",
    "pcastello@spinnakersupport.com": "Great to connect. Peter, was looking at Spinnaker Support and trying to understand what outbound signals actually catch an Oracle or SAP customer at the moment they're willing to leave vendor support. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "brooke.snow@configura.com": "Great to connect. Brooke, was looking at Configura and trying to understand what outbound plays work when the buyer is a furniture dealer or office designer evaluating 3D space planning tools. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "arnold.harden@orbussoftware.com": "Great to connect. Arnold, was looking at Orbus Software and trying to understand what signals tell your team when an enterprise is ready to move enterprise architecture off Excel vs. staying with what they have. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "max.schultz@electric.ai": "Great to connect. Max, was looking at Electric and trying to understand what outbound looks like now that your buyer is an IT ops leader at an SMB who probably cycles through two MSP candidates per quarter. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "craig.fisher@dispatchtrack.com": "Great to connect. Craig, was looking at DispatchTrack and trying to understand what outbound actually lands when every buyer has seen 20 demos that claim the same thing. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "jisenhower@officespacesoftware.com": "Great to connect. Jess, was looking at OfficeSpace Software and trying to understand what outbound signals tell you a corporate real estate leader is actually ready to reseat vs. wait. Curious to hear how others selling into real estate tech are building pipeline right now, Scott.",
    "chuck.jones@m3as.com": "Great to connect. Chuck, was looking at M3 and trying to understand what outbound plays work when your buyer is a regional hotel operator rather than a brand headquarters. Curious to hear how others selling into hospitality tech are building pipeline right now, Scott.",
    "kyle.jacobson@achievers.com": "Great to connect. Kyle, was looking at Achievers and trying to understand what outbound signals tell the team when a chief people officer is actually ready to evaluate employee recognition vs. still consolidating HRIS. Curious to hear how others selling into HR tech are building pipeline right now, Scott.",
    "karem.gonzalez@advancedmd.com": "Great to connect. Karem, was looking at AdvancedMD and trying to understand what outbound actually works when your buyer is a solo practitioner who has already been burned by a past EHR switch. Curious to hear how others selling into healthcare tech are building pipeline right now, Scott.",
    "kobrien@thegoldensource.com": "Great to connect. Kathryn, was looking at GoldenSource and trying to understand what outbound signals tell you a sell-side firm is ready to revisit its reference data architecture. Curious to hear how others selling into financial services are building pipeline right now, Scott.",
    "christian.estrada@lendio.com": "Great to connect. Christian, was looking at Lendio and trying to understand what outbound plays actually work when your ICP is a small business owner who has been pitched by seven lenders this month. Curious to hear how others selling into financial services are building pipeline right now, Scott.",
    "chris.erickson-king@orthofi.com": "Great to connect. Chris, was looking at OrthoFi and trying to understand what outbound signals cut through when your buyer is an orthodontic office manager rather than a DSO executive. Curious to hear how others selling into healthcare tech are building pipeline right now, Scott.",
    "jody.uva@buyersedgeplatform.com": "Great to connect. Jody, was looking at Buyers Edge Platform and trying to understand what outbound plays work for you when your buyer is a restaurant operator or a hospitality procurement lead. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "enelson@caisoft.com": "Great to connect. Eric, was looking at CAI Software and trying to understand what outbound plays work for CAI in graphic communications when most of the buyer side is already using a generalist MRP. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "anations@kahua.com": "Great to connect. Alicia, was looking at Kahua and trying to understand what signals tell your team when a public-sector owner is ready to replace a legacy capital projects system vs. sticking with Prolog. Curious to hear how others selling into construction tech are building pipeline right now, Scott.",
    "jcrocker@veritone.com": "Great to connect. Jeff, was looking at Veritone and trying to understand what outbound plays work for AI video analytics now that every federal agency has both budget and compliance pressure on the same decision. Curious to hear how others selling into government tech are building pipeline right now, Scott.",
    "cesar.aguilera@monarcasnacks.com": "Great to connect. Cesar, was looking at Monarca Food Solutions and trying to understand what outbound plays work when the team is building a CPG brand that competes against incumbents with 10x distribution. Curious to hear how others selling into your space are building pipeline right now, Scott.",
    "s.phillippi@bizzdesign.com": "Great to connect. Sam, was looking at Bizzdesign and trying to understand what outbound signals tell your team a business architecture leader is actually ready to add tooling vs. keep running PowerPoint diagrams. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "ethornberg@altametrics.com": "Great to connect. Eric, was looking at Altametrics and trying to understand what outbound signals tell the team when a restaurant operator is ready to consolidate scheduling, inventory, and accounting onto one platform. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "jdayal@auvik.com": "Great to connect. JD, was looking at Auvik and trying to understand what outbound signals tell the team when an IT leader at an MSP or mid-market company is ready to add network monitoring vs. keep troubleshooting manually. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "sblaine@applause.com": "Great to connect. Seth, was looking at Applause and trying to understand what outbound looks like when your ICP is a digital experience leader at a consumer brand rather than an IT security leader. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
}

FIXES_BATCH2 = {
    "ethornberg@altametrics.com": "Great to connect. Eric, was looking at Altametrics and trying to understand how the team manages outbound signal quality across two different ICPs on one roster. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "kevin.gulbransen@practicetek.com": "Great to connect. Kevin, was looking at PracticeTek and trying to understand what outbound signals catch a dental or specialty practice at the moment it's evaluating new software vs. still bundling. Curious to hear how others selling into healthcare tech are building pipeline right now, Scott.",
    "jdayal@auvik.com": "Great to connect. JD, was looking at Auvik and trying to understand what outbound signals the team trusts when selling network management across different verticals. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "sblaine@applause.com": "Great to connect. Seth, was looking at Applause and trying to understand what outbound looks like when your ICP is a digital experience leader at a consumer brand rather than an IT security leader. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "scott.mcmaster@graitec.com": "Great to connect. Scott, was looking at GRAITEC and trying to understand what outbound plays work now that AEC buyers are thinking about AI for design and for operations at the same time. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "t.martin@adform.com": "Great to connect. Tim, was looking at Adform and trying to understand what outbound signals tell your team a European agency or advertiser is actually ready to revisit the programmatic stack vs. keep rolling with Google. Curious to hear how others selling into ad and marketing tech are building pipeline right now, Scott.",
    "andrew.baker@lvt.com": "Great to connect. Andrew, was looking at LVT and trying to understand what outbound actually works for a buyer who runs a construction site or a fleet yard and has zero patience for another vendor pitch. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "david.hunt@smartrent.com": "Great to connect. David, was looking at SmartRent and trying to understand what outbound signals tell your team a multifamily operator is actually ready to roll out smart access vs. keep planning for next year. Curious to hear how others selling into real estate tech are building pipeline right now, Scott.",
    "mark.ostrosky@kandasoft.com": "Great to connect. Mark, was looking at Kanda Software and trying to understand what outbound plays work now that custom software buyers are getting pitched AI-first and offshore-plus-onshore in the same week. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "megean.parfitt@getpliant.com": "Great to connect. Megean, was looking at Pliant and trying to understand what outbound actually works in a category where every prospect has already been pitched by Brex, Ramp, and three European entrants. Curious to hear how others selling into financial services are building pipeline right now, Scott.",
    "dorian.dawson@netsmartz.com": "Great to connect. Dorian, was looking at Netsmartz and trying to understand what outbound plays land when your buyer has to choose between cyber spend and AI dev spend in the same budget meeting. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "rlombardo@deshazo.com": "Great to connect. R., was looking at DeSHAZO and trying to understand what outbound plays catch a plant manager at the moment an overhead crane starts failing inspection. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "stan.dilullo@aaseya.com": "Great to connect. Stan, was looking at Aaseya and trying to understand what outbound plays work now that the buyer is a CIO who already knows the team from the consulting side. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "lauren.wiseley@casago.com": "Great to connect. Lauren, was looking at Casago and trying to understand what outbound actually works when your buyer is an owner of a beach condo rather than a hotel corporate sales leader. Curious to hear how others selling into real estate tech are building pipeline right now, Scott.",
    "michael.hoben@bizerba.com": "Great to connect. Michael, was looking at Bizerba and trying to understand what outbound plays catch a grocer or meat processor at the moment their compliance scale fails inspection vs. just aging out. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "j.moriarty@closerstillmedia.com": "Great to connect. Jeff, was looking at CloserStill Media and trying to understand what outbound plays work for your team now that every hyperscaler wants to be the headline sponsor. Curious to hear how others selling into ad and marketing tech are building pipeline right now, Scott.",
    "megan.morgan@fpc.com": "Great to connect. Megan, was looking at FPC and trying to understand what outbound plays work when the team is selling sensors into OEMs through distributors rather than direct SaaS. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "jdevers@qeiinc.com": "Great to connect. Jerrod, was looking at QEI and trying to understand what outbound signals catch a utility at the moment it's actually ready to modernize SCADA vs. continue studying. Curious to hear how others selling into energy tech are building pipeline right now, Scott.",
    "brett.allen@workwave.com": "Great to connect. Brett, was looking at WorkWave and trying to understand what outbound plays work when your buyer is a pest control or lawn care owner-operator rather than a traditional enterprise contact. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "jerryp@nallas.com": "Great to connect. Jerry, was looking at Nallas and trying to understand what outbound plays actually work for Databricks-adjacent consulting now that every prospect has seen 15 AI pitches this quarter. Curious to hear how others selling into data and analytics are building pipeline right now, Scott.",
    "rhoney@cbnits.com": "Great to connect. Richard, was looking at CBNITS and trying to understand what outbound plays work for a fractional sales leader managing a SAP RPA practice against the SAP partner heavyweights. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "sbier@natoli.com": "Great to connect. Sandra, was looking at Natoli Engineering and trying to understand what outbound plays work when the team is selling capital equipment into pharma manufacturers who only buy on validation cycles. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "joel.lewis@budderfly.com": "Great to connect. Joel, was looking at Budderfly and trying to understand what outbound plays work when your ICP is an SMB operator who considers energy a line item not a strategy. Curious to hear how others selling into energy tech are building pipeline right now, Scott.",
    "molivero@vias3d.com": "Great to connect. Matthew, was looking at VIAS3D and trying to understand what outbound plays work when your ICP is a mechanical engineering manager at a Dassault customer rather than a greenfield PLM buyer. Curious to hear how others selling into industrial tech are building pipeline right now, Scott.",
    "will.cunningham@apiglobalsolutions.com": "Great to connect. Will, was looking at Accommodations Plus International and trying to understand what outbound plays work when your buyer is an airline crew scheduling lead with a legacy vendor and no immediate budget. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "joel.vanderpol@daxko.com": "Great to connect. Joel, was looking at Daxko and trying to understand how the post-acquisition integration changed the way the team thinks about outbound in fitness SaaS. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "george.ninikas@ortec.com": "Great to connect. George, was looking at ORTEC and trying to understand what outbound signals tell your team when a retailer is actually ready to commit to route and workforce optimization. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "brande.melton@igel.com": "Great to connect. Brande, was looking at IGEL and trying to understand what outbound plays land when the buyer is an EUC lead at a hospital or bank dealing with AI-desktop budget overlap. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "chris.dehlic@primussoft.com": "Great to connect. Chris, was looking at Primus Software and trying to understand what outbound plays actually work when your ICP is a project manager who has been burned by offshore staffing in the past. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "pamelap@interrait.com": "Great to connect. Pamela, was looking at InterraIT and trying to understand what outbound plays actually work for a legacy-modernization and QA shop competing against big Indian services firms. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "binh@infowaygroup.com": "Great to connect. Binh, was looking at Info Way Solutions and trying to understand what outbound plays actually work now that every buyer has three preferred IT-services partners on a frame agreement. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "girts.graudins@testdevlab.com": "Great to connect. Girts, was looking at TestDevLab and trying to understand what outbound plays work when your ICP is a product engineering leader who doesn't want to offshore testing. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "chris.chung@starburstdata.com": "Great to connect. Chris, was looking at Starburst and trying to understand what signals actually tell your team a buyer is ready to move past their lakehouse and start federating. Curious to hear how others selling into data and analytics are building pipeline right now, Scott.",
    "markm@climbcs.com": "Great to connect. Mark, was looking at Climb Channel Solutions and trying to understand what outbound plays work for a value-added distributor now that every ISV wants to sell direct first and worry about channel second. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "patrick.delaroza@lendscape.com": "Great to connect. Patrick, was looking at Lendscape and trying to understand what outbound plays actually catch a commercial lender at the moment they decide the incumbent AR finance platform is the blocker. Curious to hear how others selling into financial services are building pipeline right now, Scott.",
    "geasley@a5corp.com": "Great to connect. Garrett, was looking at A5 and trying to understand what outbound plays work now that every NetSuite customer is getting three partners pitching the same AI-implementation theme. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "john.toomey@wolterskluwer.com": "Great to connect. John, was looking at Enablon and trying to understand what outbound signals tell your team a chemical, pharma, or energy buyer is actually ready to replace their EHS system vs. keep customizing. Curious to hear how others selling into legal and compliance tech are building pipeline right now, Scott.",
    "marc.gemassmer@appfire.com": "Great to connect. Marc, was looking at Appfire and trying to understand what outbound signals catch an Atlassian customer at the moment they actually decide to consolidate on Appfire vs. keep stacking point apps. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "kshara@demandbase.com": "Great to connect. Kelly, was looking at Demandbase and trying to understand what patterns repeat across those four on outbound, given how different the buyer persona is each time. Curious to hear how others selling into ad and marketing tech are building pipeline right now, Scott.",
    "cody.moore@getweave.com": "Great to connect. Cody, was looking at Weave and trying to understand what outbound plays work when the team is cross-selling payments into a dental or vet customer that already uses the practice software. Curious to hear how others selling into healthcare tech are building pipeline right now, Scott.",
    "jessica.cunning@getweave.com": "Great to connect. Jessica, was looking at Weave and trying to understand what outbound signals tell your team a veterinary or optometry partner is actually ready to co-sell vs. still in early relationship. Curious to hear how others selling into healthcare tech are building pipeline right now, Scott.",
    "will.chan@igel.com": "Great to connect. Will, was looking at IGEL Technology and trying to understand what signals actually catch an EUC buyer at the moment they decide to revisit their endpoint architecture vs. stay on Windows. Curious to hear how others selling into developer tools are building pipeline right now, Scott.",
    "joey.dagostino@intentsify.io": "Great to connect. Joey, was looking at Intentsify and trying to understand what outbound plays work now that intent data is getting commoditized and the market is collapsing to five platforms. Curious to hear how others selling into ad and marketing tech are building pipeline right now, Scott.",
    "michelle.chiantera@corel.com": "Great to connect. Michelle, was looking at Parallels and trying to understand what outbound plays work now that productivity software is competing against AI-native point tools instead of Microsoft alone. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "nate.johns@practicetek.com": "Great to connect. Nate, was looking at PracticeTek and trying to understand what outbound plays work when your ICP is a dental or restaurant operator rather than a classic SaaS buyer. Curious to hear how others selling into healthcare tech are building pipeline right now, Scott.",
    "tyke.sealock@roller.software": "Great to connect. Tyke, was looking at ROLLER and trying to understand what outbound plays work when your buyer is an indoor activity operator rather than a classic SMB SaaS customer. Curious to hear how others selling into B2B SaaS are building pipeline right now, Scott.",
    "amber@vereigenmedia.com": "Great to connect. Amber, was looking at Vereigen Media and trying to understand what outbound copy actually gets opened now that every B2B marketer is drowning in syndication pitches. Curious to hear how others selling into ad and marketing tech are building pipeline right now, Scott.",
    "dina@vereigenmedia.com": "Great to connect. Dina, was looking at Vereigen Media and trying to understand what outbound plays work in content syndication now that buyers are learning to filter out vendor-sponsored content at the first line. Curious to hear how others selling into ad and marketing tech are building pipeline right now, Scott.",
}


def main():
    with open(CSV_PATH, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames
        rows = list(reader)

    # Merge: batch1 first, batch2 overwrites where both have an entry
    all_fixes = {}
    all_fixes.update(FIXES_BATCH1)
    all_fixes.update(FIXES_BATCH2)

    applied = 0
    for row in rows:
        email = row["email"].lower()
        if email in all_fixes:
            row["dm1_opener"] = all_fixes[email]
            applied += 1

    with open(CSV_PATH, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Applied {applied} fixes to {CSV_PATH}")


if __name__ == "__main__":
    main()
